### ISSUE TITLE
Custom CSS in default theme

### ISSUE THREAD

**Issue by jvican** [szeiger/ornate#2]
It would be nice if there's a straightforward way of defining custom CSS resources. For people that link the default theme but want to make some minor style fixes, it's perfect. The idea would be to copy those static resources and then link to them in the generated html files.

**Comment by szeiger** [comment]
Implemented in https://github.com/szeiger/ornate/commit/005b106aaa88dced999286658a11bcd8160f5925 and https://github.com/szeiger/ornate/commit/65c3ba59de8d026a42d1ef7b453668a20be50473
